POST http://localhost:8081/api/v1/team_dashboard
Content-Type: application/json

{
  "firstName": "aaaaaaaaaaaa",
  "lastName":"bbbbbbbbbbb",
  "objective":"ccccccccccccccccccc",
  "achievment": "0.00",
  "objectiveType": "Mission100",
  "objectiveStatus": "true",
  "comment": "test",
  "objectiveDeadline": "2021-12-01"
}
###
POST http://localhost:8081/api/v1/team_dashboard
Content-Type: application/json

{
"firstName": "lalalkas",
"lAstName":"Laneri",
"objectiveName":"Test"
}
###
DELETE http://localhost:8081/api/v1/team_dashboard/1

###
DELETE http://localhost:8081/api/v1/team_dashboard/2
###
DELETE http://localhost:8081/api/v1/team_dashboard/3
###
DELETE http://localhost:8081/api/v1/team_dashboard/4
###
PUT http://localhost:8081/api/v1/stock/7?name=door

###
GET http://localhost:8081/api/v1/team_dashboard/?firstName=Alejandro