app:
  dataSource:
    postgres:
      port: 5432
      usernam: postgres
      password: password
      host: localhost
      databaseName: dashboard
      jdbc-url: jdbc:postgresql://${app.dataSource.postgres.host}:${app}localhost:8082/dashboard
